### ISSUE TITLE
Age of Empires Dd7to9

### ISSUE THREAD

**Issue by 9xtiger** [elishacloud/dxwrapper#177]
All are perfect but the color of name player when i show the timeline changed from black to white. This make me disconect when i play with other player. Im using dd7to9 Age of empires. big thanks to you

**Comment by mirh** [comment]
https://www.gamepressure.com/download.asp?ID=81940
https://download.cnet.com/Age-of-Empires/3000-7483_4-10013361.html
https://www.moddb.com/games/age-of-empires/downloads/age-of-empires-trial-version

**Comment by elishacloud** [comment]
Thanks!  I wonder if I can test the multiplayer issues with this demo?

**Comment by elishacloud** [comment]
> All are perfect but the color of name player when i show the timeline changed from black to white.

Ok, I can reproduce this issue with the trial edition.  I have seen this kind of issue before.  Let me see if I can fix it.

**Comment by elishacloud** [comment]
It looks like this game is using a combination of GDI and DirectDraw to create the graphics.  Direct3D9 does not play nicely with GDI when in exclusive fullscreen mode.  Try enabling the `FullscreenWindowMode` option.  That should solve this issue.

**Comment by 9xtiger** [comment]
> Unfortunately, I don't have a copy of the game. This is a game I wanted to test with for a while but could not find a demo copy of it online. When you say it disconnects you from the other players, can you give me more details? What makes you think that it is dxwrapper that is causing you to get disconnected?
https://www.mediafire.com/file/fuaxaakhar6cc0d/game-de-che-1.zip/file
I still cant play with other player. I think this dxwraper is casusing me to get Disconnected because it only disconnected when i use dxwraper. If i delete that, i can play it nomally. 
It only disconnect when i or other player click to show timeline - the one that differrent between us. 
"You were disconnected because of a sync error" - when i click the timeline show.

**Comment by FunkyFr3sh** [comment]
I had out of sync errors with cnc-ddraw before with one game, the solution was D3DCREATE_FPU_PRESERVE ... Maybe give that a try as well. I haven't heard about any issues with AOE in combination with cnc-ddraw though (I don't use this flag by default, do you?)

**Comment by mirh** [comment]
> with newer builds of Windows 10 Direct3D9 got changed and this change caused GDI to not be visible when Direct3D9 is in exclusive fullscreen mode

Are you sure the problem isn't the fact that exclusive fullscreen isn't really much that anymore [actually](https://www.pcgamingwiki.com/wiki/Windows#Fullscreen_optimizations)?
"Dumb windowed" mode could just be enjoying the advantage of still retaining bitblt presentation.

**Comment by elishacloud** [comment]
> Are you sure the problem isn't the fact that exclusive fullscreen isn't really much that anymore [actually](https://www.pcgamingwiki.com/wiki/Windows#Fullscreen_optimizations)?

The issue only happens on Direct3D9.  The issue happens when you set the `Windowed` parameter of the [D3DPRESENT_PARAMETERS](https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dpresent-parameters) to `FALSE`.  If you do the same thing on Direct3D8 it works fine (no issue).  Disabling fullscreen optimizations has no effect on this issue.  There is no way in Direct3D9 for GDI graphics to be seen when `Windowed` is set to `FALSE`, as far as I have seen.

I would love to know if anyone has a fix for this because it affect lots of games when using `dd7to9` and some games when using `d3d8to9`.

BTW: Setting `Windowed` to `FALSE` in `D3DPRESENT_PARAMETERS` is what's known as exclusive fullscreen mode.  And whether it is a thing to not, the option still exists and still works.  However, it just has this bug in it with GDI graphics.

**Comment by elishacloud** [comment]
@9xtiger, I fixed an issue based on @FunkyFr3sh's comments.  Can you check this one out and see if it fixes the issue:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11236765/dxwrapper.zip)

**Comment by mirh** [comment]
> The issue only happens on Direct3D9.

I mean.. Not like GDI is gonna work with newer d3d, right?

> Disabling fullscreen optimizations has no effect on this issue.

Mhhh, I see. 
But.. even put aside that I seem to remember there was *at least* some version of W10 that used to not give a damn about that checkbox, I'd exhort you to double check with presentmon the actual window mode that you are getting. 

> BTW: Setting Windowed to FALSE in D3DPRESENT_PARAMETERS is what's known as exclusive fullscreen mode. 

Except not really, as I just sighed yesterday in #59? 
There isn't actually any way (well, out of the box at least) to get d3d8 exclusive fullscreen on an updated windows. The dll that is shipped simply doesn't even have the corresponding functions anymore.

**Comment by elishacloud** [comment]
> I mean.. Not like GDI was ever supposed/gonna to work with newer d3d, right?

Where is it documented that this is not going to work?  It worked with d3d9 on every version of Windows (Including Windows 10) until the Windows 10 [April Update](https://support.microsoft.com/en-us/help/4028685/windows-10-get-the-update).  And it still works with d3d8 on every version of Windows.

> But.. even put aside that I seem to remember there was _at least_ some version of W10 that used to not give a damn about that checkbox

I just checked on the latest released version of Windows 10 and disabling fullscreen optimizations has no effect on this issue.

> There isn't actually any way (well, out of the box at least) to get d3d8 exclusive fullscreen on an updated windows.

I understand.  I know it is not true exclusive mode.  But anyways that is what you are telling DirectX you want and that is the mode that is broken with GDI.

**Comment by elishacloud** [comment]
> Where is it documented that this is not going to work?

I found it.  The documentation is right [here](https://devblogs.microsoft.com/directx/dxgi-flip-model/#when-should-i-use-blt-model) says that the "flip" model does not support "multiple different APIs producing contents, which all layer together into the same HWND ... An example of this would be using D3D to draw a window background, and then GDI to draw something on top".

This implies that the "Blt" model _does_ support that (i.e. multiple different APIs producing contents, which all layer together into the same HWND).  Dxwrapper's `dd7to9` is using the Blt model so this should be supported.  This issue with GDI and d3d9 not working together is clearly a bug in Windows 10.

**Comment by 9xtiger** [comment]
> Anyways, here is a new build for you to try. Let me know if this works: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11225135/dxwrapper.zip)
This one worked for me. Thank you very much. Its amazing!



> @9xtiger, I fixed an issue based on @FunkyFr3sh's comments. Can you check this one out and see if it fixes the issue: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11236765/dxwrapper.zip)

And this 1 not worked. it got error in mutiplayer game. Mouse and Keyboard stuck and lagging.

**Comment by FunkyFr3sh** [comment]
> > Are you sure the problem isn't the fact that exclusive fullscreen isn't really much that anymore [actually](https://www.pcgamingwiki.com/wiki/Windows#Fullscreen_optimizations)?
> 
> The issue only happens on Direct3D9. The issue happens when you set the `Windowed` parameter of the [D3DPRESENT_PARAMETERS](https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dpresent-parameters) to `FALSE`. If you do the same thing on Direct3D8 it works fine (no issue). Disabling fullscreen optimizations has no effect on this issue. There is no way in Direct3D9 for GDI graphics to be seen when `Windowed` is set to `FALSE`, as far as I have seen.
> 
> I would love to know if anyone has a fix for this because it affects lots of games when using `dd7to9` and some games when using `d3d8to9`.
> 
> BTW: Setting `Windowed` to `FALSE` in `D3DPRESENT_PARAMETERS` is what's known as exclusive fullscreen mode. And whether it is a thing to not, the option still exists and still works. However, it just has this bug in it with GDI graphics.

Doesn't "Direct3D9EnableMaximizedWindowedModeShim" in d3d9.dll fix the issue? I'm not too sure though, I always just use opengl for these games in cnc-ddraw

**Comment by elishacloud** [comment]
> Doesn't "Direct3D9EnableMaximizedWindowedModeShim" in d3d9.dll fix the issue? I'm not too sure though, I always just use opengl for these games in cnc-ddraw

No.  I tried disabling and enabling `Direct3D9EnableMaximizedWindowedModeShim` in d3d9.dll as well as disabling and enabling fullscreen optimizations and all combinations of those.  Still does not work.  I don't have an OpenGL option, instead I use fullscreen windowed mode to solve this issue.

**Comment by elishacloud** [comment]
@9xtiger, thanks for testing this.  Can you test this one and let me know if this works also?

This one just removes the delay in writing to the screen with dxwrapper to see if this is the issue.  I want to narrow down the issue to a single thing.

Here is the update:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11240021/dxwrapper.zip)

**Comment by mirh** [comment]
> Where is it documented that this is not going to work? It worked with d3d9 on every version of Windows (Including Windows 10) 

I said newer directx, not newer windows... Though I'll grant I was kind of misremembering the [chart](https://learn.microsoft.com/en-us/windows/win32/direct3darticles/surface-sharing-between-windows-graphics-apis#api-interoperability-overview) and its implication
Glad that you eventually found something anyway, lol. 

> until the Windows 10 [April Update](https://support.microsoft.com/en-us/help/4028685/windows-10-get-the-update).

Mhh, is *this* documented somewhere? Which april are we talking about?

>  Dxwrapper's dd7to9 is using the Blt model so this should be supported. 

Well, that's what you *ask*. What you *get* isn't necessairly the same thing. 
That's why I told you to actually check the presentmode with presentmon. 

> Doesn't "Direct3D9EnableMaximizedWindowedModeShim" in d3d9.dll fix the issue?

I was going to tell you `DXMaximizedWindowedMode` just made fullscreen into borderless windowed (so it wouldn't have influenced the *presentation* mode).. but that was indeed created and [promoted](https://web.archive.org/web/20140516233958/http://msdn.microsoft.com/en-us/library/hh994464(v=vs.85).aspx) exactly to address cases like this. 

> instead I use fullscreen windowed mode to solve this issue.

I mean, that's kinda what maximized windowed mode should be AFAIK... I'm quite uneasy by this implication.

**Comment by 9xtiger** [comment]
> This one just removes the delay in writing to the screen with dxwrapper to see if this is the issue. I want to narrow down the issue to a single thing.
> 
> Here is the update: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11240021/dxwrapper.zip)

This one make disconnect. 
I want to note that if I turn "FullscreenWindowMode" on, the game will not be as smooth as when I turn it off, even though my device is i7-13700k

**Comment by elishacloud** [comment]
@9xtiger, thanks for checking.  When you say it is not as smooth with "FullscreenWindowMode" on, is that true for the build that worked above or is it just this build that is not as smooth?

Can you test with this one?  I hope this works:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11241157/dxwrapper.zip)

**Comment by 9xtiger** [comment]
> Can you test with this one? I hope this works: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11241157/dxwrapper.zip)

This one work well. 


> @9xtiger, thanks for checking. When you say it is not as smooth with "FullscreenWindowMode" on, is that true for the build that worked above or is it just this build that is not as smooth?

It getting not smooth for all of version dxwrapper. So i turned it off. Black and white name is not big problem with me. Thank you.

**Comment by elishacloud** [comment]
Thanks @9xtiger for checking on this.  I added a fix for this issue into the project.

**Comment by elishacloud** [comment]
> Mhh, is _this_ documented somewhere? Which april are we talking about?

This issue was first introduced with Windows 10 [Fall Creators Edition](https://blogs.windows.com/windowsexperience/2017/10/17/whats-new-windows-10-fall-creators-update/).  I am not aware of any documentation stating this issue.  As I showed with the [previous documentation](https://devblogs.microsoft.com/directx/dxgi-flip-model/#when-should-i-use-blt-model) this should work (not just on Direct3D9 but also on DirectX10 and DirectX11).  It is clearly a bug in Windows, AFAIK.  BTW: I think we are rehashing some of the comments from the thread [here](https://github.com/crosire/d3d8to9/issues/61).

> I mean, that's kinda what maximized windowed mode should be AFAIK... I'm quite uneasy by this implication.

Yes, me too.  Especially since the reports we are seeing is that maximized windowed mode isn't as smooth game play as exclusive fullscreen mode is.

**Comment by elishacloud** [comment]
Closing this issue as complete.

**Comment by mirh** [comment]
> This issue was first introduced with Windows 10 [Fall Creators Edition](https://blogs.windows.com/windowsexperience/2017/10/17/whats-new-windows-10-fall-creators-update/)

I would recommend you to use build numbers next time, for better peace/clarity/easiness of mind (even because *April* isn't in *Autumn*.. is it?)
With this said, I'm afraid [every](https://old.reddit.com/r/Windows10/comments/c5ahfc/bug_dx9dx11_games_do_not_enter_independent_flip/) W10 release is basically its one special mix of quirks. 
1709 specifically was kind of the "peak flip mode", since they allegedly decided ([there](https://old.reddit.com/r/pcgaming/comments/ck13z9/psa_windows_10_1903_will_now_ignore_the_disable/evjtrcz/) and only [there](https://www.resetera.com/threads/psa-in-most-cases-you-dont-need-exclusive-fullscreen-anymore.422177/post-64517024)) to also upgrade windowed borderless to it. 
The following Windows versions shouldn't have been *that* forceful, but the devil is in the detail. 

> BTW: I think we are rehashing some of the comments from the thread https://github.com/crosire/d3d8to9/issues/61.

Good memory, that kind of interop talk was exactly what I had in mind. Though I'll grant my "brainstorming pitches" there sounds really stupid in hindsight...
But now I really feel like I have quite the bombshell that I could drop for that, when I have time. ^^

>  Especially since the reports we are seeing is that maximized windowed mode isn't as smooth game play as exclusive fullscreen mode is.

... I believe last month I was going to tell you that you can't really be sure of which mode you are *actually* in, unless you actively check for it (and AFAIK that in turns could only mean using ETW to query Windows). 

But does https://github.com/elishacloud/dxwrapper/compare/238d6db00bf3bcf4f539820edfeabd4ed3a2fe7c...91cb50669e06f78c956581b793096c580d83eb40 mean that, indeed, all our observation above were misplaced? And that maximized windowed never actually engaged?

**Comment by elishacloud** [comment]
> I would recommend you to use build numbers next time

Agreed.

> you can't really be sure of which mode you are _actually_ in

True.  But in this case it does not really matter.  As long as you request exclusive fullscreen access by an app then this issue exists, whether or not you are _actually_ in the mode doesn't matter.  There must be some way to solve this, but I have not figured it out yet.

> But does [238d6db...91cb506](https://github.com/elishacloud/dxwrapper/compare/238d6db00bf3bcf4f539820edfeabd4ed3a2fe7c...91cb50669e06f78c956581b793096c580d83eb40) mean that, indeed, all our observation above were misplaced? And that maximized windowed never actually engaged?

Yes, the setting in dxwrapper was broken, and maximized windowed never actually engaged.  However, I have since fixed the issue and tested both with dxwrapper and with Windows compatibility mode.  The issue still happens whether maximized windowed is engaged or not.

**Comment by elishacloud** [comment]
I found a real fix for this issue by calling [`Direct3D9SetSwapEffectUpgradeShim()`](https://github.com/crosire/reshade/commit/3fe0b050706fb9f3510ed48d619cad71f7cb28f2#diff-74772e50e2921e0bf69f0470e81d072d30c071b6e4b30af8cfd6cda58cf249eeR35) with parameter of `0`.  This changes the present mode to "Hardware: Legacy Flip", which is the same mode that DirectDraw and Direct3D8 is using.  For more details on the issue see comments [here](https://github.com/narzoul/DDrawCompat/issues/269#issuecomment-1843829944).

Here is the fix for this in dxwrapper:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/13607653/dxwrapper.zip)
