### ISSUE TITLE
[Freelancer (2003)] Odd-looking shadow appears when camera moves up/down (D3d8to9 only)

### ISSUE THREAD

**Issue by BC46** [elishacloud/dxwrapper#268]
When opening the equipment dealer menu in the video game Freelancer (2003), the camera moves up before the interface appears. Whenever this is done with the `D3d8to9` option enabled, an odd-looking shadow appears below the ship. If `D3d8to9` is turned off, this doesn't occur.

I've tested this on DxWrapper versions 1.1.6900.22 and 1.1.6972.22; the problem could be seen on both.

`D3d8to9 = 1`:

https://github.com/elishacloud/dxwrapper/assets/45081813/9e46e579-6993-4a4e-8640-b27265a9ae85

`D3d8to9 = 0`:

https://github.com/elishacloud/dxwrapper/assets/45081813/0e1ecb4b-2010-4d19-acd9-cd4c6587a557

**Comment by elishacloud** [comment]
I wonder if this is related to #136.

**Comment by BC46** [comment]
I'm not entirely sure since presumably the linked issue relates to legacy D3D8, whereas the shadow issue only occurs when converting D3D8 to 9.

**Comment by BC46** [comment]
I've created a PIX snapshot of the shadow bug while running the game with just d3d8to9 v1.12.0: [ShadowBugFreelancerD3d9.zip](https://github.com/elishacloud/dxwrapper/files/15131182/ShadowBugFreelancerD3d9.zip). Thought it may give some insights into what could cause the bug to occur.

**Comment by Squall-Leonhart** [comment]
This happens natively too, likely because of the unification of nvidia shadow buffers mentioned in #75 after G80.

I still have functional NV30 hardware on XP where it doesn't occur, but theres a christmas tree set up in front of that old pc right now so getting to it for tracing won't be possible till atleast jan 1st.

**Comment by BC46** [comment]
Any insights or ideas on how a solution can be implemented?

**Comment by elishacloud** [comment]
> likely because of the unification of nvidia shadow buffers mentioned in [#75](https://github.com/elishacloud/dxwrapper/issues/75) after G80.

From the PIX snapshot I don't see any sign that shadow maps are being used by this game.  At least it is not used in the frame collected by PIX.

> Any insights or ideas on how a solution can be implemented?

No, I am not quite sure what is happening.  I may need to test it myself.  The PIX data hasn't helped me much.

**Comment by BC46** [comment]
I looked at the disassembly and found that the shadow is actually just a texture:

<img width="64" height="64" alt="Image" src="https://github.com/user-attachments/assets/51cc4073-71c1-4a68-b82b-fce5acf455e4" />

Also, I had another look at the PIX snapshot and noticed the `IDirect3DDevice9::SetRenderState(D3DRS_ZFUNC, D3DCMP_LESSEQUAL)` call right before the shadow is rendered. The reason this stood out to me is because earlier I had dealt with the depth test when investigating [a different render-related issue in Freelancer](https://github.com/BC46/FLSharp/issues/15). I traced the `SetRenderState` call in question to a function in `flmaterials.dll`, a DLL responsible for rendering various materials in the game. Just for fun I patched the binary to use the zfunc `D3DCMP_ALWAYS` instead of `D3DCMP_LESSEQUAL`. As far as I can tell, this completely fixes the bug. There's a possibility that the bug can also be fixed by changing the cull mode but I haven't tested that.

The patch:
```
flmaterials.dll, E90C, 04 -> 08 = use the zfunc D3DCMP_ALWAYS instead of D3DCMP_LESSEQUAL when rendering the shadow material
```

Here's a PIX snapshot I took with the patch applied:

[ShadowBugFixFreelancerD3d9_PIX.zip](https://github.com/user-attachments/files/23052567/ShadowBugFixFreelancerD3d9_PIX.zip)

**Comment by elishacloud** [comment]
> I traced the `SetRenderState` call in question to a function in `flmaterials.dll`, a DLL responsible for rendering various materials in the game. Just for fun I patched the binary to use the zfunc `D3DCMP_ALWAYS` instead of `D3DCMP_LESSEQUAL`. As far as I can tell, this completely fixes the bug.

Interesting.  Thanks for researching this!  It is very helpful.  The question I have is why does this work in native d3d8?  What is different about d3d8 vs d3d9 here?

_Edit: this also confirms that this issue is unrelated to d3d8 shadow maps._

**Comment by elishacloud** [comment]
After thinking about this, I wonder if this has to do with the conversion of ZBIAS (d3d8) to DepthBias (d3d9).  Here are some updates to test:

ZBIAS conversion fix (see [here](https://github.com/crosire/d3d8to9/pull/209)):  [dxwrapper_zbias_fix.zip](https://github.com/user-attachments/files/23063870/dxwrapper_zbias_fix.zip)

Disable ZBIAS and convert `D3DCMP_LESS` to `D3DCMP_LESSEQUAL`:  [dxwrapper_zbias_disable.zip](https://github.com/user-attachments/files/23063875/dxwrapper_zbias_disable.zip)

_Note: disabling ZBIAS may cause artifacts and other issues.  This is just to test if it solves the shadow issue.  It will help identify the issue._

**Comment by BC46** [comment]
With both updated versions, the shadow is not visible at all:

<img width="1989" height="965" alt="Image" src="https://github.com/user-attachments/assets/429789d5-9765-4bef-af24-fafb0a08a0a7" />

**Comment by elishacloud** [comment]
@BC46, thanks for testing.  Looks like my last code had a mistake.  However, I took a better look at the PIX output and I think I might have a solution.

Can you try this build:  ~dxwrapper.zip~

_Note: I think the odd-looking shadow is a bug in d3d8to9.  It should have shown no shadow at all since ZFunc was set to D3DCMP_LESS and both the shadow and the floor have the same Z-level._

_Edit: this build had a minor bug in it._

**Comment by elishacloud** [comment]
Please try with this build instead:  [dxwrapper.zip](https://github.com/user-attachments/files/23108978/dxwrapper.zip)

**Comment by BC46** [comment]
The shadow is still invisible unfortunately. I've attached two PIX snapshots - one was taken with the release build v1.4.7900.25 and the other with the latest build you sent.

[PIX.zip](https://github.com/user-attachments/files/23110046/PIX.zip)

**Comment by elishacloud** [comment]
Thanks for the PIX snapshots.  Everything looks good from those.  I think the issue is the slight difference in how d3d8 and d3d9 handle depth values and computing.  I've added a slight depthbias to the shadow to help it work similarly to d3d8.

Can you try this build:  [dxwrapper.zip](https://github.com/user-attachments/files/23131240/dxwrapper.zip)

**Comment by BC46** [comment]
Still no visible shadow: [FreelancerD3d9DxWrapperLatest2.zip](https://github.com/user-attachments/files/23135785/FreelancerD3d9DxWrapperLatest2.zip). Is the game doing something unusual to render the shadow?

**Comment by elishacloud** [comment]
Looks like I had two different issues with all my build in this thread:

1. The epsilon that I used was too small for the bit count.
2. I thought the ZBIAS was always set to 0.  But it seems that it was my misreading the PIX output.

Assuming I fixed these two issues correctly, I think this may fix the shadows:  [dxwrapper.zip](https://github.com/user-attachments/files/23137171/dxwrapper.zip)

**Comment by BC46** [comment]
Nice, I can see the shadow now! However, the bug is still present: [FreelancerD3d9DxWrapperShadowBugLatest.zip](https://github.com/user-attachments/files/23141577/FreelancerD3d9DxWrapperShadowBugLatest.zip). When the camera moves up, the shadow seems to "appear" quicker than in the `D3d8to9 = 1` video I posted.

**Comment by elishacloud** [comment]
Ok, I hope this will work.  I am doing the same fix that you mentioned above, changing the `D3DRS_ZFUNC` to `D3DCMP_ALWAYS`.  I am not sure if this will break other games but I hope it will fix this issue.

Here is the testing build: [dxwrapper.zip](https://github.com/user-attachments/files/23143518/dxwrapper.zip)

**Comment by BC46** [comment]
Indeed, this fixes the issue. Though this time I noticed new render-related issues in the game. For instance, normally the ringed cushion below the ship is partially hidden from this angle, but now it is entirely visible.

<img width="1173" height="651" alt="Image" src="https://github.com/user-attachments/assets/ddec5891-d760-44a4-b573-36413c56a42a" />

**Comment by elishacloud** [comment]
> Though this time I noticed new render-related issues in the game.

That is what I was afraid of.  Ok, I think it seems like I need to make the DepthBias larger for these cases.  Can you try these builds and let me know which one solves the issue:

Add Depth Bias to shadows:  [dxwrapper_DepthBias.zip](https://github.com/user-attachments/files/23153901/dxwrapper_DepthBias.zip)

Uses a larger epsilon for all depth bias:  [dxwrapper_Larger_Epsilon.zip](https://github.com/user-attachments/files/23153903/dxwrapper_Larger_Epsilon.zip)

Note: If the larger epsilon build doesn't work please send me a PIX of this one.

**Comment by BC46** [comment]
The Depth Bias build fixes the issue as well but some percentage of the cushion which is normally hidden is still visible.

<img width="1122" height="647" alt="Image" src="https://github.com/user-attachments/assets/7213f613-01ab-45b7-bfed-0464b35bb5e2" />

The larger epsilon build on the other hand fixes the issue without any repercussions, at least as far as I can tell. Could there be potentially unwanted side effects in other scenes due to the larger epsilon?

Also not sure if something changed since the latest release build of dxwrapper, but I just noticed that with all the builds you sent me in this thread, the window mode gamma shader does not seem to be working anymore, even if I manually enable it in the config file under `[d3d9]`.

**Comment by elishacloud** [comment]
> The larger epsilon build on the other hand fixes the issue without any repercussions, at least as far as I can tell. Could there be potentially unwanted side effects in other scenes due to the larger epsilon?

I don't think so.  I guess maybe the larger epsilon is the right way to fix this.  I was always trying to make the epsilon as small as possible.  But it seems like it actually needs to be large enough to handle these cases.

> Also not sure if something changed since the latest release build of dxwrapper, but I just noticed that with all the builds you sent me in this thread, the window mode gamma shader does not seem to be working anymore, even if I manually enable it in the config file under `[d3d9]`.

I changed the way it works.  It now only works if you either set `WindowModeGammaShader` to `2` or if you have either `EnableWindowMode` or `FullscreenWindowMode` enabled.

**Comment by BC46** [comment]
Understood, thanks for explaining.

**Comment by BC46** [comment]
@elishacloud I tested the larger epsilon build with another scene and noticed some shadows being visible even though there are objects in front. I shall provide a PIX snapshot when I have time.

**Comment by elishacloud** [comment]
Ok, rather than guessing what the right value is I made it configurable.  Here is the new build:  [dxwrapper.zip](https://github.com/user-attachments/files/23176176/dxwrapper.zip)

I added two new options:

```ini
DepthBiasScale             = 0
SlopeBiasScale             = 0
```

If you set `DepthBiasScale` to about `1300` then should be similar to the  larger epsilon build above.  The smaller the number the better and the less chance that it will cause side effects.  There is no limit to the value you can choose, but I don't think you will want to or need to set it larger than 1300.

The other value `SlopeBiasScale` may help reduce the issue.  This number also has no upper limit but I doubt you will want to put this much larger than a couple hundred.  This one will almost certainly need to be smaller than `DepthBiasScale`.  Setting this should reduce the size needed for `DepthBiasScale`.

Good options to maybe start with is:

```ini
DepthBiasScale             = 600
SlopeBiasScale             = 50
```

Let me know what numbers are best for these.  Ideally the smallest number that has no visual oddities should be the best.

**Comment by BC46** [comment]
Thanks for this build! I played around with the options, but it seems that no matter what values I enter, I am unable to hide the background shadows in the latter scene. I even tried some very low values.

For example, with the following config:
```ini
DepthBiasScale             = 6
SlopeBiasScale             = 1
```
The highlighted background shadows are visible even though they should be hidden:

<img width="1615" height="739" alt="Image" src="https://github.com/user-attachments/assets/cefea651-0061-49ea-9fb8-743415fbb195" />

Here's a PIX snapshot of the scene: [FreelancerD3d9ShadowBugDepthAndSlopeBias.zip](https://github.com/user-attachments/files/23197803/FreelancerD3d9ShadowBugDepthAndSlopeBias.zip).

**Comment by elishacloud** [comment]
Thanks for testing.  Did you try setting both to `0`?  It's also possible that the issue may be related to the `SlopeBiasScale`.  You can set that to 0 and then just use the `DepthBiasScale`.

_Edit: I believe `SlopeBiasScale` is the cause.  This object has a deep slope and is causing the bias to be too great._

Try this build.  I removed `SlopeBiasScale` because I don't think it is very useful and is causing an issue:  [dxwrapper.zip](https://github.com/user-attachments/files/23198290/dxwrapper.zip)

**Comment by BC46** [comment]
This new build appears to be for DirectX 7 games since `ddraw.dll` is included and `Dd7to9` is enabled in the config file. I enabled `D3d8to9` and then tested the build. Though the zip doesn't include `d3d8.dll` so if that was updated, then I may not have the latest version.

I tested the build with the default value `DepthBiasScale = 0`. The only notable difference it made is that now the background shadow doesn't cover the entire head of the man on the right.

<img width="285" height="168" alt="Image" src="https://github.com/user-attachments/assets/e70ced66-ff1f-41d0-bea4-08968f6bdcff" />

I also tried some different values like `500` and `1000` but that yielded similar results to my previous test.

**Comment by elishacloud** [comment]
> This new build appears to be for DirectX 7 games since `ddraw.dll` is included and `Dd7to9` is enabled in the config file.

Oh, I gave you the wrong one.  It's still the latest build so it should be fine.

> The only notable difference it made is that now the background shadow doesn't cover the entire head of the man on the right.

That is weird.  Is this a new issue?  I ask because if `DepthBiasScale` is disabled then it should work basically the same as the current dxwrapper build.  I wonder if there is an easy way for me to test this.

The issue is that d3d8 uses ZBIAS and d3d9 uses DEPTHBIAS and they don't work the same.  I'm trying to tweak DEPTHBIAS to make it work as similar as possible.

**Comment by BC46** [comment]
> That is weird. Is this a new issue? I ask because if DepthBiasScale is disabled then it should work basically the same as the current dxwrapper build.

The thing is that this particular shadow should not be visible at all since the object which is in front of the shadow is supposed to hide it. Here's what the scene looks like in D3D8:

<img width="1607" height="747" alt="Image" src="https://github.com/user-attachments/assets/596c8aac-3ca4-4b12-b8ee-bd674142bae1" />

> I wonder if there is an easy way for me to test this.

If you want I can help you set up the game so you can test it on your system.

> The issue is that d3d8 uses ZBIAS and d3d9 uses DEPTHBIAS and they don't work the same. I'm trying to tweak DEPTHBIAS to make it work as similar as possible.

I see. Sadly there doesn't seem to be a trivial way to do a 1:1 conversion.

**Comment by elishacloud** [comment]
> If you want I can help you set up the game so you can test it on your system.

Yes, that would be great.  These things are very difficult to troubleshoot remotely.

**Comment by BC46** [comment]
Many abandonware sites offer a download link for Freelancer since the game is no longer officially sold. However, abandonware is not a legal term and thus I don't know whether GitHub will allow me to provide links to such sites. Some time ago I uploaded my original CD of the game to archive.org which you can find here: https://archive.org/details/freelancer-english_202502. If I'm not allowed to post this link then I can remove it. The only modification I made to the files is that I included the official No-CD EXE since the original EXE uses SafeDisc which no longer works on modern Windows versions.

To install the game, extract the downloaded zip to a location somewhere on your main (C:/) drive and run the `SETUP.EXE` file. If you don't trust it, don't hesitate to run it in a VM. During the installation it may ask you to choose an installation path. I recommend not installing to Program Files as that may cause permission-related issues. Once you've installed it, the game *should* work out of the box. Try launching it for the first time (three intros should play at the start which you can skip by pressing Esc). After it successfully launched, close the game and download this zip: [SaveFiles.zip](https://github.com/user-attachments/files/23209342/SaveFiles.zip). Extract the two files in there to the game's save folder: `Documents\My Games\Freelancer\Accts\SinglePlayer`. I also recommend installing [Jason's Freelancer Patch (JFLP)](http://adoxa.altervista.org/freelancer/index.html) since it adds bug fixes, widescreen support, and also automatically skips the three intros at the start. If you installed the game to Program Files, you need to run `jflp.exe` as an admin. There exists also an official 1.1 Patch but we don't need that in this case.

Once you've installed JFLP and put in the save files, launch the game again and open the "OPTIONS" menu. You should be able to select your main monitor's resolution, provided the JFLP installation was successful. Next, open "PERFORMANCE OPTIONS" and check if all settings are set to max (this ensures the shadows are actually rendered). Then go back to "MAIN MENU" and restart the game to make sure the widescreen fix works properly. After starting the game again, select "LOAD GAME". You should now see two save files called Freeport 9 and Manhattan. Freeport 9 is the save file that puts you in the greenish looking base from most of my PIX snapshots. 

<img width="640" height="360" alt="Image" src="https://github.com/user-attachments/assets/fe98a2fe-f0c5-4cde-9f82-fcc7e7c33375" />

To test the original shadow bug, click the cog icon at the top (Equipment Dealer). Then either click on the man standing at the very front, or click the icon of the man raising his hand at the top. Now the camera moves up and a menu appears. To go back, either press Esc or click the "X" at the top-right of the menu. Now press F1 to open the pause menu. Here you can go back to the main menu to exit, or click "LOAD GAME" to load the other save file. After loading the Manhattan save file, it'll bring you to the scene from my most recent PIX snapshot. 

<img width="640" height="360" alt="Image" src="https://github.com/user-attachments/assets/b6b41d46-47cb-478a-a437-3d9b8e3c1ec8" />

If you need to re-enter the scene, click any of the non-highligted icons at the top and after that click the cog icon again.

**Comment by elishacloud** [comment]
Thanks for the detailed instructions!  I am able to reproduce both issues.

Interestingly enough, one of the issue has to do with setting DEPTHBIAS to 0.0f rather than -0.0f.  Theoretically these numbers should both be treated the same, but apparently they are not.

**Comment by elishacloud** [comment]
Ok, try this one.  It should be a proper fix for this without requiring any configuration:  [dxwrapper.zip](https://github.com/user-attachments/files/23225107/dxwrapper.zip)

**Comment by BC46** [comment]
Good to hear that you managed to get the game working! I tested the build and everything looks fine. Well done!

**Comment by Squall-Leonhart** [comment]
> Interestingly enough, one of the issue has to do with setting DEPTHBIAS to 0.0f rather than -0.0f. Theoretically these numbers should both be treated the same, but apparently they are not.

These are recast to dwords once processed by the api, and interpretted back once the driver is reached.

The float itself is always signed in the normal IEEE 754 way - negative values have the sign bit set, positive values don't

-0.0 as a float has bit pattern 0x80000000, which if interpreted as an integer becomes -2147483648

**Comment by elishacloud** [comment]
> -0.0 as a float has bit pattern 0x80000000, which if interpreted as an integer becomes -2147483648

Yes, I understand that.  But given the formula used for DEPTHBIAS from the documentation it is hard to understand how 0.0f and -0.0f would be different.  Here is the formula given in the [documentation](https://learn.microsoft.com/en-us/windows/win32/direct3d9/depth-bias):

```c++
Offset = m * D3DRS_SLOPESCALEDEPTHBIAS + D3DRS_DEPTHBIAS
```

Adding -0.0f or adding 0.0f shouldn't change the output of the end result.

What's more confusing is that the value defaults to 0.0f, however, if I use that default value then it breaks a shadow in the game.  The only fix for this is to set the value to -0.0f;

**Comment by Squall-Leonhart** [comment]
Did you typo here?

```
	float Value = -0.0f;
	ProxyInterface->SetRenderState(D3DRS_POINTSIZE_MIN, *(DWORD*)&Value);
```

should it not be

```
float Value = -0.0f;
ProxyInterface->SetRenderState(D3DRS_DEPTHBIAS, *(DWORD*)&Value);
```

> What's more confusing is that the value defaults to 0.0f, however, if I use that default value then it breaks a shadow in the game. The only fix for this is to set the value to -0.0f;

could it be, that to simulate the farther bias of D3D8, you use a negative floating-point value for D3DRS_DEPTHBIAS because the D3D9/OpenGL depth coordinate system maps the near plane to a small value (like 0) and the far plane to a large value (like 1)?

**Comment by elishacloud** [comment]
> Did you typo here?

Yes, good catch.  I fixed it.  Thanks!

> could it be, that to simulate the farther bias of D3D8, you use a negative floating-point value for D3DRS_DEPTHBIAS because the D3D9/OpenGL depth coordinate system maps the near plane to a small value (like 0) and the far plane to a large value (like 1)?

Interesting.  Good point.  That could be the reason.

**Comment by elishacloud** [comment]
Fixed the the latest check-in to d3d8to9.

**Comment by elishacloud** [comment]
Changing the DepthBias to work with Freelancer caused other games to break because Freelancer requires a larger bias than most other games.  So with the latest build (9a46c08374f2fda24b442f63e56191dec5729785) when using `d3d8to9` you need to set the `DepthBiasFactor` to `160` to fix this issue.  This should make the shadows and everything else in this game work correctly.

**Comment by BC46** [comment]
A fellow Freelancer modder told me that the problem still happens in some other scenes, even with dxwrapper v1.5.8100.25 while `DepthBiasFactor` is set to `160`. Here's an example of one such scene with dxwrapper and d3d8to9 enabled. Look at the bottom-left corner as the camera moves:

https://github.com/user-attachments/assets/ff7e5d7e-2ba2-4565-b038-82e7c99bce37

Interestingly, in D3D8 this shadow is not visible at all:

https://github.com/user-attachments/assets/8a045fe0-19bc-424c-9556-e8c6737d4cbd

Are there any suggestions for `DepthBiasFactor` and `DepthBiasDropOffValue` values such that this particular shadow becomes hidden just like in D3D8 while not breaking any of the other shadows?

@elishacloud, if you still have Freelancer installed, here's a save file that takes you right to the scene: [Kurile.zip](https://github.com/user-attachments/files/25154037/Kurile.zip). To reproduce the issue, first click the cog icon, then click the icon with the two arrows (Change View). When the camera has moved up, keep clicking the Change View icon to move the camera between the two points.

<img width="683" height="201" alt="Image" src="https://github.com/user-attachments/assets/41aa0519-7224-45d2-820e-3a4f81f0f0c9" />

**Comment by elishacloud** [comment]
> Interestingly, in D3D8 this shadow is not visible at all:

Even native D3D8 has an issue here. If you look carefully, you can see that the shadow for the fin on the ship in the bottom left-hand corner appears and disappears as the screen moves.

If you want behavior closer to D3D8, you can choose a number smaller than 160 for `DepthBiasFactor`. If you want to try to fix the shadow so it works correctly, then try a number larger than 160. To test this, increase the value in increments of 50. Once you go too high, decrease it in increments of 10 until you get into the right ballpark.

For example, try setting the bias factor to 210. If that doesn't break anything and doesn't fix the issue, then try 260, and so on. If, for instance, 260 causes problems, then try 250, then 240, until you find a value that works. For testing, I would focus on the three areas from this thread known to be susceptible to shadow issues: Freeport 9, Manhattan, and now Kurile.

You will probably want to keep `DepthBiasDropOffValue` disabled. It is not needed for this game.

_Note: for this game I think it is just a matter of trial and error until you find the right value that works and causes the least issues._

**Comment by BC46** [comment]
Thanks for the hints. I shall play around with the `DepthBiasFactor` value when I have time.

> Even native D3D8 has an issue here. If you look carefully, you can see that the shadow for the fin on the ship in the bottom left-hand corner appears and disappears as the screen moves.

I looked at the D3D8 video again frame-by-frame but I don't notice any shadow appearing or disappearing near that corner. Could you take a screenshot and highlight the area where you see it happening?

**Comment by elishacloud** [comment]
> Could you take a screenshot and highlight the area where you see it happening?

Yes, see below.  I highlighted it in the picture.  However, after zooming in I found out it isn't a shadow but rather a box on the plane that disappears and reappears as you change views.  See here:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/980c2bae-d0f2-4216-84de-cf842804de1a" />

BTW: if you find a good `DepthBiasFactor` it would be good to add it to this thread for future posterity's sake.

**Comment by BC46** [comment]
> See here:

Ah, but that is actually a LOD issue. The latest version of JFLP (patch that includes the widescreen fix) has a bug where the LOD transitions occur too early on widescreen. This happens because Freelancer's LODs are partially determined by the FOV, but JFLP doesn't consider this. An updated DLL that resolves this problem is available but it isn't included in the JFLP installer.

I maximized the LOD ranges using [flplusplus](https://github.com/FLHDE/flplusplus) and now there shouldn't be any more disappearing objects in the scene, even in D3D8:

https://github.com/user-attachments/assets/d0f48d47-979f-4006-b8e4-aa1b0657920a

> BTW: if you find a good `DepthBiasFactor` it would be good to add it to this thread for future posterity's sake.

Sure. I tried a bunch of different values, hoping to find one that causes no issues in any of the three scenes. Unfortunately, it seems I've hit a dead end; anything lower than 90 breaks Freeport 9, whereas anything higher than 80 breaks Kurile. I also tried a high value like 220 to make the shadow in Kurile entirely visible, but that broke other things in the same scene. Furthermore, I noticed in a new scene (Crete) that a shadow would appear even with a `DepthBiasFactor` of 80; I had to decrease it to 60 to fix it. Given the circumstances, I think 60 is the overall best value as this only breaks Freeport 9 marginally. It just hides a tiny portion of the shadow which I think you'd only notice when comparing D3D8 and D3D9 side-by-side.

**Comment by elishacloud** [comment]
> I maximized the LOD ranges using [flplusplus](https://github.com/FLHDE/flplusplus) and now there shouldn't be any more disappearing objects in the scene, even in D3D8:

Ok, great.

> Given the circumstances, I think 60 is the overall best value as this only breaks Freeport 9 marginally. It just hides a tiny portion of the shadow which I think you'd only notice when comparing D3D8 and D3D9 side-by-side.

My suggestion is to to use 60 for the `DepthBiasFactor` and then if you have the ability to modify the engine (as you seem to be able to to given that you can change the LOD range) you can change the game to send a ZBIAS of 2 rather than 1 for this particular shadow in `Freeport 9` that doesn't work right.  Hopefully that will make all the shadows work as good or better than they did in d3d8.

**Comment by BC46** [comment]
Although I'd love to admit that I have full control over the engine and can modify whatever I want, unfortunately it's not really the case here. The LOD range modification feature is implemented by simply hooking the game's ini reader where it reads lines like these for every model used in the game:
```ini
LODranges = 0, 40, 60, 140, 300, 1000
```
Every number listed is then multiplied by a user-defined constant.

Fortunately, I have another idea. When we looked into Freelancer's infamous lighting bug that happened after some Windows update (https://github.com/elishacloud/dxwrapper/issues/134), I explained how the game uses Lua scripts to create D3D8 lights in a scene. These same scripts also define models that are dynamically added to the scene, including the ship. Therefore, inside the script I can increase the ship's y-position by a tiny bit such that there is no more z-fighting between the shadow and the floor. I just tried that and it indeed does the trick. 

I'll continue using 60 for the `DepthBiasFactor` and if I ever come across the issue again in another scene, I'll update its Lua script. Okay, I'm satisfied with this solution. Thanks for all your help and support!

**Comment by elishacloud** [comment]
Ok, very good.  I'll close this issue for now.
