### ISSUE TITLE
StarTrekArmada1 Backgrounds

### ISSUE THREAD

**Issue by LordFowlIte** [elishacloud/dxwrapper#28]
I Followed the instructions to download the fix for the game, and It ran. It even loads the missions, mostly. The game only loads in the textures for the ships and stations, It has the dilithium moons and asteroid belts. Just missing the space backgrounds and the build zones. They all still exist as certain places cant be utilized for building, so the assets are there, there are just no textures for them. All textures are visible in the cinematic mode, all textures are also visible in the cutscenes. It's not massive, but it is rather annoying, I was wondering what I could do to fix the issue?
![img-4969](https://user-images.githubusercontent.com/41041922/42492698-f4e04332-83ce-11e8-819c-8268b6ca071f.JPG)
![img-4968](https://user-images.githubusercontent.com/41041922/42492700-f5e3aee0-83ce-11e8-886f-0177f86f06c8.JPG)
![img-4967](https://user-images.githubusercontent.com/41041922/42492703-f73ccd62-83ce-11e8-961b-d7109589a495.JPG)
![img-4966](https://user-images.githubusercontent.com/41041922/42492672-dae0c344-83ce-11e8-9f20-2b46b73842ce.JPG)

**Comment by elishacloud** [comment]
Yes, this same issue was reported on [fleetops.net](https://www.fleetops.net/forums/topic?f=31&t=12841&p=205906&e=205906).  This seems to only happen on systems with integrated graphics adapters.

I am working on a wrapper that will convert ddraw to d3d9, which should fix this issue, but it will take a while for me to get this done.

**Comment by CookiePLMonster** [comment]
Worth noting that Colin McRae Rally 2.0 has something similar - on Intel GPUs, several background boxes are missing. It's a D3D7 game so ddraw is also in play there.

**Comment by elishacloud** [comment]
Yes, I believe these issues may be related.  Both of them are related to the Intel GPU and are using D3D7.  I think Intel did not implement something correctly or has some missing functionality.  Anyways I have not spent time troubleshooting this because I plan to just convert these all to d3d9, which should make it run better on any modern GPU.

**Comment by elishacloud** [comment]
I updated the NVidia drivers on my laptop and made a number of fixes to dxwrapper and I am no longer seeing this issue.  Can you try updating to the latest NVidia drivers and using the fix below?

Download the update from here: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/2872436/dxwrapper.zip)

_Note: I am also using Windows 10 (Version 1809), which seems to have some fixes.  You can download it [here](https://www.microsoft.com/en-us/software-download/windows10)._

**Comment by yochenhsieh** [comment]
Hi, you should add the updated wrapper on the Armada page. It helps with my desktop PC, Windows 7 and AMD driver 19.5.2.

**Comment by elishacloud** [comment]
Yes, I plan to update soon.  I has been over a year since my last release.

**Comment by yochenhsieh** [comment]
Hello, just want to report that this updated version can also fix Star Trek: Generations. Symptom after driver update: click option while in stellar cartography or press esc in FPS mission causes game to crash. Before the driver update no wrapper was required.

**Comment by daundfron** [comment]
Hello people! 

First of all, thank you Elisha (@elishacloud) for effort regarding playing Star Trek Armada 1 on modern systems! After all this time, I believe many people still want to play this 20-year old game, even on Win10! In my opinion, far better game than its sequel (Star Trek Armada 2).

Secondly, I'd like to report issue myself. I've installed game, than applied 1.2 and 1.3 patches and than Elisha's fix and even fix update.

Now, far as I can tell I can play missions, no problems with textures, grid, models etc.
However, changing settings in the graphics menu causes crash. Honestly, for me that isn't such a big deal, because game actually "remembered" changes I've done there (resolution, graphics detail)!

But, big issue is trying to play INSTANT ACTION (single player - no missions). I got crash / black screen immediately when I press LAUNCH button. Even changing map when I'm setting game up causes crash. **Is this known issue and can be something done about it?**

Thank you in advance for answer!

**Comment by elishacloud** [comment]
@daundfron, I tested this with the lasted unreleased dxwrapper build and it works for me.  I have done a lot of fixes since the last Star Trek Armada 1 fix release.  Try the one below and see if it works.

Just unzip this into your Star Trek Armada 1 game folder:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/3639024/dxwrapper.zip)

_Note: I have heard from other users that this fix also works on Star Trek Armada 2, but I don't have the game so I cannot test it._

**Comment by daundfron** [comment]
@elishacloud I have tested latest build, but sadly, it did not work. Same crash after map choosing or launch button... On the other hand, changing game settings causes screen freezing and music will still play... Missions are still running ok, just like before. 
Missions and instant action "should be" almost same thing (except for cut scenes) so what could cause issue?
Do you need my system specs maybe?
And can you make a save on random map and uploaded it here? I'd like to see does loading instant action map make any difference (at least on my machine).

**Comment by elishacloud** [comment]
Interesting.  If you upload your log file that has details about your machine.  Try disabling the `DDrawCompatExperimental` option in the ini file to see if that helps.

Here is a save from an Instant Action game: [s2.zip](https://github.com/elishacloud/dxwrapper/files/3645064/s2.zip)

**Comment by daundfron** [comment]
@elishacloud here are some news...
First, I tried loading save game you have provided, and I actually got to the loading screen, and after 3/4 of loading was done - game crashed.
Than I tried disabling DDrawCompatExperimental and that unfortunately ended same as above.
In attachment is log file you requested from Armada's Logs folder.

And one note from "history". On the Windows 7 Ultimate I used to play Armada without any problem. Ok, now and than, game would crash sometimes, but that wasn't issue.
**But trying to play my custom made maps would make game crash instantly, just like with this issue.** And playing someone else's maps was ok. Really weird.
[logfile.txt](https://github.com/elishacloud/dxwrapper/files/3648753/logfile.txt)

**Comment by elishacloud** [comment]
Hello @daundfron, sorry I wasn't clear.  I meant the dxwrapper.log file.  Can you attach the dxwrapper.log file?

Also can you verify your compatibility settings?  It should have all options disabled, like this:

![](https://raw.githubusercontent.com/elishacloud/wiki-attachments/master/dxwrapper/Games/Star%20Trek%20Armada%201/Compatibility.png)

**Comment by daundfron** [comment]
Yeah, I had ticked compatibility mode for Win XP SP2 and Run this program as an administrator. I disabled both, but once again nothing changed and game crashed. **That was yesterday.**

**And this morning,** I wanted to attach you here log file you need, but with newer date and now INSTANT ACTION actually works. I tried launching 2 different maps and I even managed to load my own save. Loading your save causes game to crash. Anyway, good news.

Now, I'll try to create my own map to see will game crash like I mentioned before.
Do you still need log file than?

And one question regarding Armada.exe file. I used to modify this game heavily (using .odf files - in which you can change ships' weaponry, shields, crew, etc.) I'm just curious is there any code in that Armada.exe file regarding number of races in game. By default, there are 4 races, and I'd like to add one more. Is there any way to find that out?

**Comment by elishacloud** [comment]
> **And this morning,** I wanted to attach you here log file you need, but with newer date and now INSTANT ACTION actually works. I tried launching 2 different maps and I even managed to load my own save.

Ok, great.  I'm glad you got it working.

> Do you still need log file than?

No.  As long is it is working for you then all is good.

> I'm just curious is there any code in that Armada.exe file regarding number of races in game. By default, there are 4 races, and I'd like to add one more. Is there any way to find that out?

Unfortunately I really don't know.  I didn't dig into the code of Armada that much.  I just worked on fixing the issues that I found.

**Comment by daundfron** [comment]
@elishacloud Thanks anyway mate! You did a great job making Star Trek Armada playable on modern systems. I shared this thread on couple of other sites dedicated to the game so other people can test your fix. Hopefully, they will be able to play game too.
Once again, thank you help and really fast response!

**Comment by elishacloud** [comment]
Fixed.  Closing issue.

**Comment by pi-bie** [comment]
I'm experiencing the same issue as the OP. While the game starts with the September '19 dxwrapper.zip contents installed, they don't fix the problem for me. The older fix from February '19 has the game getting stuck on the splash screen.

**Comment by accwebs** [comment]
This seems to still be unresolved unless I'm just being dense and missing the solution.

I've tried various versions of dxwrapper and the background still does not draw.

The good news is that disabling map 'shroud' works around the issue.  But this does not work for story mode - single player.

**Comment by elishacloud** [comment]
I have a feeling this issue is related to D3D9On12.  I'll need to test for this later.
