### ISSUE TITLE
Simcity 4 has graphical glitches

### ISSUE THREAD

**Issue by YouYouTheBoxx** [elishacloud/dxwrapper#409]
I am playing simcity 4 using your dxwrapper as to support my ultrawide (32:9) resolution but it seems it creates artifacts on screen.

Fauna in-game seems to be z-fighting with the terrain which causes some parts of it to actually be masked for a portion of pixels.

Here's my config:

[General]
RealDllPath                = AUTO
WrapperMode                = AUTO
LoadCustomDllPath          = 
ExcludeProcess             = 
IncludeProcess             = 
RunProcess                 = 
WaitForProcess             = 0
DisableLogging             = 0

[Plugins]
LoadPlugins                = 0
LoadFromScriptsOnly        = 0

[Compatibility]
Dd7to9                     = 1
D3d8to9                    = 0
DDrawCompat                = 1
Dinputto8                  = 0
DisableGameUX              = 1
EnableDdrawWrapper         = 1
EnableD3d9Wrapper          = 0
EnableDinput8Wrapper       = 0
EnableDsoundWrapper        = 0
EnableOpenDialogHook       = 0
WinVersionLie              = off
WinVersionLieSP            = 0
HandleExceptions           = 0
SingleProcAffinity         = 0

[DDrawCompat]
DDrawCompat20              = 0
DDrawCompat21              = 0
DDrawCompat32              = 0
DDrawCompatDisableGDIHook  = 0
DDrawCompatNoProcAffinity  = 0

[ddraw]
DdrawOverrideBitMode       = 0

[Dd7to9]
DdrawAutoFrameSkip         = 0
DdrawEmulateSurface        = 0
DdrawEmulateLock           = 0
DdrawForceMipMapAutoGen    = 0
DdrawFixByteAlignment      = 0
DdrawEnableByteAlignment   = 0
DdrawIntroVideoFix         = 0
DdrawRemoveScanlines       = 0
DdrawRemoveInterlacing     = 0
DdrawReadFromGDI           = 0
DdrawWriteToGDI            = 0
DdrawDisableDirect3DCaps   = 0
DdrawLimitTextureFormats   = 0
DdrawLimitDisplayModeCount = 0
DdrawCustomWidth           = 0
DdrawCustomHeight          = 0
DdrawUseNativeResolution   = 0
DdrawOverrideWidth         = 0
DdrawOverrideHeight        = 0
DdrawIntegerScalingClamp   = 0
DdrawMaintainAspectRatio   = 0
; override stencil format for 24-bit depth buffer (reduces Z-fighting)
DdrawOverrideStencilFormat = 75

[d3d9]
AnisotropicFiltering       = 0
AntiAliasing               = 0
EnableVSync                = 0
ForceVsyncMode             = 0
ShowFPSCounter             = 0
OverrideRefreshRate        = 0
LimitDisplayModeCount      = 0
CustomDisplayWidth         = 0
CustomDisplayHeight        = 0
LimitPerFrameFPS           = 0
EnableWindowMode           = 0
WindowModeBorder           = 0
SetInitialWindowPosition   = 0
InitialWindowPositionLeft  = 0
InitialWindowPositionTop   = 0
FullscreenWindowMode       = 0
ForceExclusiveFullscreen   = 0
ForceMixedVertexProcessing = 0
ForceSystemMemVertexCache  = 0
SetSwapEffectShim          = 0
DisableMaxWindowedMode     = 0
ForceDirect3D9On12         = 1
GraphicsHybridAdapter      = 1

[FullScreen]
FullScreen                 = 0
ForceWindowResize          = 0
WaitForWindowChanges       = 0

[dinput8]
DeviceLookupCacheTime      = 0
FilterNonActiveInput       = 0
FixHighFrequencyMouse      = 0
MouseMovementFactor        = 0
MouseMovementPadding       = 0

[dsound]
Num2DBuffers               = 0
Num3DBuffers               = 0
ForceCertification         = 0
ForceExclusiveMode         = 0
ForceSoftwareMixing        = 0
ForceHardwareMixing        = 0
ForceHQ3DSoftMixing        = 0
ForceNonStaticBuffers      = 0
ForceVoiceManagement       = 0
ForcePrimaryBufferFormat   = 0
PrimaryBufferBits          = 16
PrimaryBufferSamples       = 44100
PrimaryBufferChannels      = 2
AudioClipDetection         = 0

**Comment by elishacloud** [comment]
Can you attach your dxwrapper log?

I noticed that you have some settings enabled that are either not compatible or could cause issues.  Can you try disabling `DdrawOverrideStencilFormat` and `ForceDirect3D9On12` options?  Either of these could cause issues.

**Comment by elishacloud** [comment]
Ok, try this build.  I fixed a zbuffer issue that affected this game.

Here is the fixed build: [dxwrapper.zip](https://github.com/user-attachments/files/21478224/dxwrapper.zip)

**Comment by Luminatrixx** [comment]
> Can you attach your dxwrapper log?
> 
> I noticed that you have some settings enabled that are either not compatible or could cause issues. Can you try disabling `DdrawOverrideStencilFormat` and `ForceDirect3D9On12` options? Either of these could cause issues.

I already tried to disable them but same. Also, it lags a lot specifically in that game.

**Comment by Luminatrixx** [comment]
> Ok, try this build. I fixed a zbuffer issue that affected this game.
> 
> Here is the fixed build: [dxwrapper.zip](https://github.com/user-attachments/files/21478224/dxwrapper.zip)

I'm gonna try that now thanks.

EDIT: It seems my issue isn't fixed plus gives a new bug: ALT+TAB the game makes game render (not UI) black and gray).

<img width="5120" height="1440" alt="Image" src="https://github.com/user-attachments/assets/d467072c-0f6b-4a57-8f1d-c63973caf9f0" />

**Comment by Luminatrixx** [comment]
Here's the associated full log:
[dxwrapper-simcity 4.log](https://github.com/user-attachments/files/21534264/dxwrapper-simcity.4.log)

**Comment by elishacloud** [comment]
> EDIT: It seems my issue isn't fixed plus gives a new bug: ALT+TAB the game makes game render (not UI) black and gray).

When you say a new issue do you mean a newly found issue or did this used to work?  It seems like this is an old issue with dxwrapper.  There are a number of games that have Alt+Tab issues just like this and I am not quite sure what the right fix is for them.  Try disabling `ForceDirect3D9On12` and instead enable `D3d9to9Ex`.

**Comment by Luminatrixx** [comment]
> > EDIT: It seems my issue isn't fixed plus gives a new bug: ALT+TAB the game makes game render (not UI) black and gray).
> 
> When you say a new issue do you mean a newly found issue or did this used to work? It seems like this is an old issue with dxwrapper. There are a number of games that have Alt+Tab issues just like this and I am not quite sure what the right fix is for them. Try disabling `ForceDirect3D9On12` and instead enable `D3d9to9Ex`.

I mean this is a new issue introduced with the new build you gave me. I'll try switching to D3d9to9Ex.

**Comment by Luminatrixx** [comment]
Also, not to complain on your great work but do you have any idea why dgVodoo gives way better performances than your wrapper ? Can something be done on my end to improve that ? thanks.

**Comment by elishacloud** [comment]
> I mean this is a new issue introduced with the new build you gave me. I'll try switching to D3d9to9Ex.

That is weird because the Alt+Tab issue happens on all the builds I tested.  Can you tell me which build works with Alt+Tab for you?

> Also, not to complain on your great work but do you have any idea why dgVodoo gives way better performances than your wrapper ? Can something be done on my end to improve that ?

Performance can be improved.  I don't know what dgVoodoo2 is doing as it isn't open source.  However, this game uses a lot of zbuffer copies and things like that which are very slow in d3d9, which is what dxwrapper uses.  dgVoodoo2 doesn't use d3d9 it instead converts the game to d3d11/d3d12, which may not have the same limitations.  Many games run much faster with dxwrapper than with dgVoodoo2.

However, I would need to do performance profiling to see exactly what is causing the game to run slow for you.

**Comment by elishacloud** [comment]
It appears that this game has some internal FPS cap at 30.  The game keeps dropping the FPS back down to 30.  dxwrapper can handle between 170 and 300 FPS for this game but something outside of dxwrapper is delaying the game after it calls BeginScene() before it calls any other DirectDraw function.

You can see the FPS cap if you enable `ForceVsyncMode` (make sure to keep `EnableVSync` disabled) and `ShowFPSCounter`.  Then zoom in or out and see the FPS increases but then after a few seconds the game slows it down again until it hits 30 FPS.

I am not sure what dgVoodoo2 is doing to get around this internal game cap but maybe there is a patch for this game that disable that FPS cap?

**Comment by elishacloud** [comment]
I see what is happening.  If the game doesn't have anything new to draw it just waits and only draws the screen 30 times a second.  However, when there is something to draw it will draw it right away.  I only tested this with an empty map.

With a busy map I can see the slowdown.  It is not because of any specific bottlenecks.  The issue is that the game calls the Draw call hundreds or even thousands of times per frame!  Even though the Draw call is very fast (way less than 1ms) it still adds up.  The biggest slowdown is the CriticalSection call.  Also, needing to lock the Index Buffer each call takes some time.

**Comment by elishacloud** [comment]
Ok, try this build.  I removed some CriticalSection calls and disabled the non-working blitter.  This should be faster and fully functional.

Here is the testing build: [dxwrapper.zip](https://github.com/user-attachments/files/21539704/dxwrapper.zip)

**Comment by Luminatrixx** [comment]
> Ok, try this build. I removed some CriticalSection calls and disabled the non-working blitter. This should be faster and fully functional.
> 
> Here is the testing build: [dxwrapper.zip](https://github.com/user-attachments/files/21539704/dxwrapper.zip)

So I tested your new build and now the game crashes right away after getting into menu. Also my screen gets cut-out: I can only see 25% of the game screen (and that happens at start).

**Comment by elishacloud** [comment]
That's weird it doesn't crash for me.  Try this one:  [dxwrapper.zip](https://github.com/user-attachments/files/21562041/dxwrapper.zip)

**Comment by Luminatrixx** [comment]
> That's weird it doesn't crash for me. Try this one: [dxwrapper.zip](https://github.com/user-attachments/files/21562041/dxwrapper.zip)

very strange: it's the same.

[dxwrapper-simcity 4.log](https://github.com/user-attachments/files/21565072/dxwrapper-simcity.4.log)

**Comment by elishacloud** [comment]
I see this line in your logs:

```log
5940 11:35:58.180 m_IDirectDrawX::CreateD9Device Recreate device! Last create: null->WND(00F81050,GDriverClass--Software,{0,-24,5120,1416})  Windowed: 1->1 7040x1440->7040x1440 0x44->0x44
```

It seems like the game is running in windowed mode.  Did you recently switch to windowed mode?  How can you switch this game to windowed mode?

**Comment by elishacloud** [comment]
I see the following from your logs:

```log
5940 11:35:52.884 "C:\GOG Games\SimCity 4 Deluxe Edition\Apps\SimCity 4.exe" -CustomResolution:enabled -r5120x1440x32 -d:directx -w
5940 11:35:52.896 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation WinXPSp3 HighDpiAware RunAsAdmin"
```

1. Based on the resolution it appears that you are trying to run the game across multiple monitors.  That might be the issue.  Try running it in fullscreen on just one window to see if that is the issue.
2. I noticed you are running this with "WinXPSp3" compatibility option enabled.  Try disabling this and running it without the compatibility mode enabled.

**Comment by Luminatrixx** [comment]
> I see the following from your logs:
> 
> ```
> 5940 11:35:52.884 "C:\GOG Games\SimCity 4 Deluxe Edition\Apps\SimCity 4.exe" -CustomResolution:enabled -r5120x1440x32 -d:directx -w
> 5940 11:35:52.896 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation WinXPSp3 HighDpiAware RunAsAdmin"
> ```
> 
> 1. Based on the resolution it appears that you are trying to run the game across multiple monitors.  That might be the issue.  Try running it in fullscreen on just one window to see if that is the issue.
> 2. I noticed you are running this with "WinXPSp3" compatibility option enabled.  Try disabling this and running it without the compatibility mode enabled.

Ok I missed those details for you to understand:
That resolution is because I'm using a Samsung Odyssey G9.
Also, I'm not running the WinXPSp3 compat mode at all, very weird it tells that in the logs.

**Comment by elishacloud** [comment]
Try this one.  I fixed several issues with invalid rects that you may be having: 

[dxwrapper.zip](https://github.com/user-attachments/files/21587657/dxwrapper.zip)

_Edit: I found an issue that could be causing the crash.  Just updated the build here._

**Comment by elishacloud** [comment]
Can you try the latest release of dxwrapper?  This should fix the glitches and it should play much faster.

**Comment by Squall-Leonhart** [comment]
> Performance can be improved. I don't know what dgVoodoo2 is doing as it isn't open source. However, this game uses a lot of zbuffer copies and things like that which are very slow in d3d9, which is what dxwrapper uses. dgVoodoo2 doesn't use d3d9 it instead converts the game to d3d11/d3d12, which may not have the same limitations. Many games run much faster with dxwrapper than with dgVoodoo2.

i don't know what this user is doing, DGVoodoo is a hell of a lot slower on SC4 when scrolling the map towards the edges.

> It appears that this game has some internal FPS cap at 30. The game keeps dropping the FPS back down to 30. dxwrapper can handle between 170 and 300 FPS for this game but something outside of dxwrapper is delaying the game after it calls BeginScene() before it calls any other DirectDraw function.

Only when world sim is running, paused its uncapped
Theres a plugin that disables the behavior @ https://github.com/caspervg/sc4-disable-fps-limits

> I am not sure what dgVoodoo2 is doing to get around this internal game cap?

It doesn't.

**Comment by elishacloud** [comment]
Closing this issue, as it is fixed in the latest release.
