### ISSUE TITLE
FFVIII - alpha palette entries

### ISSUE THREAD

**Issue by AlfredoDore** [elishacloud/dxwrapper#431]
This program is almost completely fixing FFVIII for PC from 2000, what are the parameters that I should apply in the .ini?
[dxwrapper-ff8.log](https://github.com/user-attachments/files/22188972/dxwrapper-ff8.log)

**Comment by Mitradis** [comment]
Its ddraw game. You need only ddraw.dll from stubs and Dd7to9 = 1

**Comment by Squall-Leonhart** [comment]
> Its ddraw game. You need only ddraw.dll from stubs and Dd7to9 = 1. Other settings in [d3d9] as you want.

its a d3d6 game and requires paletted textures

**Comment by elishacloud** [comment]
Is this still an issue?  As @Squall-Leonhart mentioned you need the `ddraw.dll` stub and you only need to enable the `Dd7to9` option.

**Comment by AlfredoDore** [comment]
> Is this still an issue? As [@Squall-Leonhart](https://github.com/Squall-Leonhart) mentioned you need the `ddraw.dll` stub and you only need to enable the `Dd7to9` option.

Yes, it continues with artifacts.

**Comment by Squall-Leonhart** [comment]
does it look like this?

<img width="639" height="477" alt="Image" src="https://github.com/user-attachments/assets/954410c2-68d3-42da-a16d-69006ee68a81" />

**Comment by AlfredoDore** [comment]
> does it look like this?
> 
> <img alt="Image" width="639" height="477" src="https://private-user-images.githubusercontent.com/1098176/508563204-954410c2-68d3-42da-a16d-69006ee68a81.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjIwMjA2NDksIm5iZiI6MTc2MjAyMDM0OSwicGF0aCI6Ii8xMDk4MTc2LzUwODU2MzIwNC05NTQ0MTBjMi02OGQzLTQyZGEtYTE2ZC02OTAwNmVlNjhhODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMDFUMTgwNTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDkyYjM2ZWFlYmI1M2MyYmVmZjcxYzAzMDYzYWQ2NGZhYTg0MTgzZDA4ZGYyNzIwMWQ3MmYzMWUwOGY1N2VjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.h-YzJ77Q6hHlbNxq0jhGya-IP65doyPiTMNqJVV_WV4">

Yes, These black bars are graphical errors.

**Comment by Squall-Leonhart** [comment]
This means paletted textures aren't implemented correctly for the D3D9 renderer, probably a lack of a pre-conversion for P8 to X8R8G8B8?

**Comment by elishacloud** [comment]
I suspect this is the issue:

```log
13220 13:05:55.559 m_IDirectDrawPalette::InitInterface Warning: alpha palette entries are not implemented.
```

I never added alpha support to palette textures.  So far I had not run into any game that used it.  I will need to add support for that.

**Comment by AlfredoDore** [comment]
> I suspect this is the issue:
> 
> ```
> 13220 13:05:55.559 m_IDirectDrawPalette::InitInterface Warning: alpha palette entries are not implemented.
> ```
> 
> I never added alpha support to palette textures. So far I had not run into any game that used it. I will need to add support for that.

I know other games, but they're also Japanese; I suppose compatibility will be better now.

**Comment by elishacloud** [comment]
This issue may have been fixed in: https://github.com/elishacloud/dxwrapper/commit/cc40852f2a6c2067d872c12f95d051a93f99a977

Can you retest with the latest build [here](https://github.com/elishacloud/dxwrapper/actions/runs/27806509057).

**Comment by AlfredoDore** [comment]
> This issue may have been fixed in: [cc40852](https://github.com/elishacloud/dxwrapper/commit/cc40852f2a6c2067d872c12f95d051a93f99a977)
> 
> Can you retest with the latest build [here](https://github.com/elishacloud/dxwrapper/actions/runs/27806509057).

I'll try it, I'll let you know in a moment if it worked or not.

**Comment by AlfredoDore** [comment]
No, but the letters no longer show errors in the main menu, but the errors persist on the battlefields.
