### ISSUE TITLE
[d3d9] Space Siege invisible cursor

### ISSUE THREAD

**Issue by AronNemeth2001** [elishacloud/dxwrapper#455]
This game has a known issue where the mouse cursor fails to render for some reason (it does actually appear on the loading screen of the game but then disappears when the menu loads). There is a fix on Pcgamingwiki for it, but it is more of a workaround (basically run it in borderless windowed with BorderlessFullscreen). It would be nice if you could look into it, as dxwrapper works with the game but doesn't fix the issue, but having a solution that isn't dependent on other software that you have to always run with the game would be good.

[dxwrapper-spacesiege.log](https://github.com/user-attachments/files/23504447/dxwrapper-spacesiege.log)

.

**Comment by elishacloud** [comment]
> a workaround (basically run it in borderless windowed with BorderlessFullscreen).

You can enable the `FullscreenWindowMode` in dxwrapper to force borderless windowed mode.

Did this issue always happen even on older Windows XP systems or was it broken by some Windows update?

**Comment by AronNemeth2001** [comment]
> You can enable the `FullscreenWindowMode` in dxwrapper to force borderless windowed mode.

Thanks, that seems to have done it! The cursor now appears. Only issue is, the game refuses to run in windowed mode if in-game resolution is set at the native res of the monitor (it shows an error window about it then switches to fullscreen, which makes the issue occur, as setting windowed in game is necessary for either dxwrapper or borderlessgaming to fix the issue). I guess I can work around the later on desktop if i enable virtual super resolution (as that will make the game think it is not at desktop resolution), but that's not an option on a laptop. Also I needed to enable "EnableWindowMode" in dxwrapper config too, the cursor "jumps" downwards otherwise when you click and doesn't recognize clicks on the game UI.

> Did this issue always happen even on older Windows XP systems or was it broken by some Windows update?

I don't know. I do have an old XP laptop lying about, might try to see if it works on that if I have the time.

Edit: EnableWindowMode may be not actually necessary. The cursor jumping when clicking issue seems to be solved by clicking when the game is loading (I guess it is trying to grab the cursor or something that fails when the game is already running, but clicking during loading captures the cursor properly).

**Comment by elishacloud** [comment]
> Edit: EnableWindowMode may be not actually necessary. The cursor jumping when clicking issue seems to be solved by clicking when the game is loading

I have seen this issue with another game.  I believe it is related to the game window losing focus with dxwrapper.

**Comment by elishacloud** [comment]
> The cursor jumping when clicking issue seems to be solved by clicking when the game is loading

I think the latest build should resolve this issue.

> Only issue is, the game refuses to run in windowed mode if in-game resolution is set at the native res of the monitor (it shows an error window about it then switches to fullscreen, which makes the issue occur, as setting windowed in game is necessary for either dxwrapper or borderlessgaming to fix the issue).

You can keep the game set to fullscreen mode and just set windowed mode in dxwrapper.ini.

Here is the updated build:  [dxwrapper.zip](https://github.com/user-attachments/files/23557962/dxwrapper.zip)

**Comment by AronNemeth2001** [comment]
Thanks for the new build, the cursor jumping no longer occurs, but sadly the cursor issue still remains, as the cursor only works if the in-game windowed option is used, dxwrapper's own override doesn't seem to work.

Also, I tired to see if this occurs on XP but I couldn't get the game files copied to my older machine due to an USB issue. Will that again to see if it's an OS issue. Altough there are some reports of this issue happening with Dungeon Siege 2 too, which uses the same engine, and the same windowed trick also works on that game, so this may be a general issue of the game engine.

Also I just found out that [DXVK actually fixed this issue in the past](https://github.com/doitsujin/dxvk/issues/3020#issue-1430468484) so I guess that's what I'll use for the moment. That link has a description of the actual cause of the issue (something with how the game implements a software cursor), so it may be helpful.

**Comment by GenesisFR** [comment]
Dungeon Siege 2 does indeed have the same issue and it appeared since the Windows 10 Creators Update (version 1703). DXVK fixed the issue for DS2 but not for its expansion Broken World.

Common workarounds are to use Killah's fix, WineD3D or run the game windowed.
